### ISSUE TITLE
npm build errors on a fresh template

### ISSUE THREAD

**Issue by ashevat** [reshufflehq/reshuffle#238] opened 2019-09-19 18:14 UTC
<img width="906" alt="Screen Shot 2019-09-19 at 11 10 44 AM" src="https://user-images.githubusercontent.com/2354171/65269618-668ac780-dace-11e9-8ad3-d52ffe313797.png">

Steps to reproduce:
1) remix the class counter
2) download the zip
3) run npm build

see attached for error.

**Comment by vogre** [comment] 2019-09-19 18:34
Duplicate of #212.

**Closed by vogre** 2019-09-19 18:34 UTC
